### ISSUE TITLE
use arel between, instead of chaining after and before together

### ISSUE THREAD

**Issue by dburry** [TylerRick/active_record_date_range_scopes#2]
In the accompanying pull request #1 , I'm changing the `*_between` scope to use arel's `between` operator, instead of chaining arel's `letq` and `gteq` together by chaining the `*_after` and `*_before` scopes together...

This does 2 things:

1. It may in certain circumstances make it more time and resource efficient, when the database has an optimized between type operator.  For example, it might take greater advantage of indexes, or other resource enhancements, by making it one operation instead of two.
2. It gets rid of this deprecation warning in Rails 6.1.8 (and the breakage in Rails 7):
```
DEPRECATION WARNING: Merging ("enrollments"."cached_latest_followup_date" >= '2018-01-01 07:00:00') and
("enrollments"."cached_latest_followup_date" <= '2018-01-03 06:59:59.999999') no longer maintain both conditions,
and will be replaced by the latter in Rails 7.0. To migrate to Rails 7.0's behavior, use
`relation.merge(other, rewhere: true)`. (called from block in delegate_date_range_scopes at
/Users/dburry/vop/active_record_date_range_scopes/lib/active_record/date_range_scopes.rb:170)
```

For more information on this change in Rails 7, see: https://www.mintbit.com/blog/rails-7-dot-0-and-merging-activerecord-conditions

**Comment by TylerRick** [comment]
Resolved by #1. Thanks!
